#!/bin/bash

# make map

init_map() {

	cursol 0 0

	ECHO '+-------------------------------------------------------------------------------+'
	ECHO '|                                                                               |'
	ECHO '|                                                                               |'
	ECHO '|                                                                               |'
	ECHO '|                                                                               |'
	ECHO '|                                                                               |'
	ECHO '|                                                                               |'
	ECHO '|                                                                               |'
	ECHO '|                                                                               |'
	ECHO '|                                                                               |'
	ECHO '|                                                                               |'
	ECHO '|                                                                               |'
	ECHO '|                                                                               |'
	ECHO '|                                                                               |'
	ECHO '|                                                                               |'
	ECHO '|                                                                               |'
	ECHO '|                                                                               |'
	ECHO '|                                                                               |'
	ECHO '|                                                                               |'
	ECHO '|                                                                               |'
	ECHO '|                                                                               |'
	ECHO '+-------------------------------------------------------------------------------+'
}
