#!/bin/bash

source ../common/common

# program

init_map() {
	cursol 1 1
	ECHO '+-----------------------------------------------------------------------------+ \c'

	i=2
	while [ $i -le 23 ]; do
		cursol 1 $i
		ECHO '|                                                                             | \c'

		i=$((i + 1))
	done

	cursol 1 24
	ECHO '+-----------------------------------------------------------------------------+ \c'
}

# main

trap '' $SIGINT $SIGQUIT $SIGTSTP

init_tty
init_map

x=40
y=12

old_sec=$SECONDS

while :
do
	cursol $x $y
	key=timeout
	if [ $SECONDS = $old_sec ]; then
		IFS= read -s -n 1 -t 1 key
	fi
	case "$key" in
		timeout)
			old_sec=$SECONDS
			if ((y < 23)); then
				y=$((y + 1))
			fi
			;;
		q)
			break
			;;
		h|D|4)
			if [ $x -gt 2 ]; then
				x=$((x - 1))
			else
				beep
			fi
			;;
		j|B|2)
			if [ $y -lt 23 ]; then
				y=$((y + 1))
			else
				beep
			fi
			;;
		k|A|8)
			if [ $y -gt 2 ]; then
				y=$((y - 1))
			else
				beep
			fi
			;;
		l|C|6)
			if [ $x -lt 78 ]; then
				x=$((x + 1))
			else
				beep
			fi
			;;
	esac
done

quit_tty
exit

